/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50733
Source Host           : localhost:3306
Source Database       : sanaksys

Target Server Type    : MYSQL
Target Server Version : 50733
File Encoding         : 65001

Date: 2022-10-05 09:04:16
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for bank
-- ----------------------------
DROP TABLE IF EXISTS `bank`;
CREATE TABLE `bank` (
  `bank_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(150) COLLATE utf8_unicode_ci NOT NULL,
  `code` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `status` enum('1','2') COLLATE utf8_unicode_ci NOT NULL DEFAULT '1' COMMENT '1 = Dalam Negri , 2 = Luar Negri',
  PRIMARY KEY (`bank_id`)
) ENGINE=InnoDB AUTO_INCREMENT=136 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of bank
-- ----------------------------
INSERT INTO `bank` VALUES ('1', 'BANK BRI', '002', '1');
INSERT INTO `bank` VALUES ('2', 'BANK EKSPOR INDONESIA', '003', '1');
INSERT INTO `bank` VALUES ('3', 'BANK MANDIRI', '008', '1');
INSERT INTO `bank` VALUES ('4', 'BANK BNI', '009', '1');
INSERT INTO `bank` VALUES ('5', 'BANK DANAMON', '011', '1');
INSERT INTO `bank` VALUES ('6', 'PERMATA BANK', '013', '1');
INSERT INTO `bank` VALUES ('7', 'BANK BCA', '014', '1');
INSERT INTO `bank` VALUES ('8', 'BANK BII', '016', '1');
INSERT INTO `bank` VALUES ('9', 'BANK PANIN', '019', '1');
INSERT INTO `bank` VALUES ('10', 'BANK ARTA NIAGA KENCANA', '020', '1');
INSERT INTO `bank` VALUES ('11', 'BANK NIAGA', '022', '1');
INSERT INTO `bank` VALUES ('12', 'BANK BUANA IND', '023', '1');
INSERT INTO `bank` VALUES ('13', 'BANK LIPPO', '026', '1');
INSERT INTO `bank` VALUES ('14', 'BANK NISP', '028', '1');
INSERT INTO `bank` VALUES ('15', 'AMERICAN EXPRESS BANK LTD', '030', '1');
INSERT INTO `bank` VALUES ('16', 'CITIBANK N.A.', '031', '1');
INSERT INTO `bank` VALUES ('17', 'JP. MORGAN CHASE BANK, N.A.', '032', '1');
INSERT INTO `bank` VALUES ('18', 'BANK OF AMERICA, N.A', '033', '1');
INSERT INTO `bank` VALUES ('19', 'ING INDONESIA BANK', '034', '1');
INSERT INTO `bank` VALUES ('20', 'BANK MULTICOR TBK.', '036', '1');
INSERT INTO `bank` VALUES ('21', 'BANK ARTHA GRAHA', '037', '1');
INSERT INTO `bank` VALUES ('22', 'BANK CREDIT AGRICOLE INDOSUEZ', '039', '1');
INSERT INTO `bank` VALUES ('23', 'THE BANGKOK BANK COMP. LTD', '040', '1');
INSERT INTO `bank` VALUES ('24', 'THE HONGKONG & SHANGHAI B.C.', '041', '1');
INSERT INTO `bank` VALUES ('25', 'THE BANK OF TOKYO MITSUBISHI UFJ LTD', '042', '1');
INSERT INTO `bank` VALUES ('26', 'BANK SUMITOMO MITSUI INDONESIA', '045', '1');
INSERT INTO `bank` VALUES ('27', 'BANK DBS INDONESIA', '046', '1');
INSERT INTO `bank` VALUES ('28', 'BANK RESONA PERDANIA', '047', '1');
INSERT INTO `bank` VALUES ('29', 'BANK MIZUHO INDONESIA', '048', '1');
INSERT INTO `bank` VALUES ('30', 'STANDARD CHARTERED BANK', '050', '1');
INSERT INTO `bank` VALUES ('31', 'BANK ABN AMRO', '052', '1');
INSERT INTO `bank` VALUES ('32', 'BANK KEPPEL TATLEE BUANA', '053', '1');
INSERT INTO `bank` VALUES ('33', 'BANK CAPITAL INDONESIA, TBK.', '054', '1');
INSERT INTO `bank` VALUES ('34', 'BANK BNP PARIBAS INDONESIA', '057', '1');
INSERT INTO `bank` VALUES ('35', 'BANK UOB INDONESIA', '058', '1');
INSERT INTO `bank` VALUES ('36', 'KOREA EXCHANGE BANK DANAMON', '059', '1');
INSERT INTO `bank` VALUES ('37', 'RABOBANK INTERNASIONAL INDONESIA', '060', '1');
INSERT INTO `bank` VALUES ('38', 'ANZ PANIN BANK', '061', '1');
INSERT INTO `bank` VALUES ('39', 'DEUTSCHE BANK AG.', '067', '1');
INSERT INTO `bank` VALUES ('40', 'BANK WOORI INDONESIA', '068', '1');
INSERT INTO `bank` VALUES ('41', 'BANK OF CHINA LIMITED', '069', '1');
INSERT INTO `bank` VALUES ('42', 'BANK BUMI ARTA', '076', '1');
INSERT INTO `bank` VALUES ('43', 'BANK EKONOMI', '087', '1');
INSERT INTO `bank` VALUES ('44', 'BANK ANTARDAERAH', '088', '1');
INSERT INTO `bank` VALUES ('45', 'BANK HAGA', '089', '1');
INSERT INTO `bank` VALUES ('46', 'BANK IFI', '093', '1');
INSERT INTO `bank` VALUES ('47', 'BANK CENTURY, TBK.', '095', '1');
INSERT INTO `bank` VALUES ('48', 'BANK MAYAPADA', '097', '1');
INSERT INTO `bank` VALUES ('49', 'BANK JABAR', '110', '1');
INSERT INTO `bank` VALUES ('50', 'BANK DKI', '111', '1');
INSERT INTO `bank` VALUES ('51', 'BPD DIY', '112', '1');
INSERT INTO `bank` VALUES ('52', 'BANK JATENG', '113', '1');
INSERT INTO `bank` VALUES ('53', 'BANK JATIM', '114', '1');
INSERT INTO `bank` VALUES ('54', 'BPD JAMBI', '115', '1');
INSERT INTO `bank` VALUES ('55', 'BPD ACEH', '116', '1');
INSERT INTO `bank` VALUES ('56', 'BANK SUMUT', '117', '1');
INSERT INTO `bank` VALUES ('57', 'BANK NAGARI', '118', '1');
INSERT INTO `bank` VALUES ('58', 'BANK RIAU', '119', '1');
INSERT INTO `bank` VALUES ('59', 'BANK SUMSEL', '120', '1');
INSERT INTO `bank` VALUES ('60', 'BANK LAMPUNG', '121', '1');
INSERT INTO `bank` VALUES ('61', 'BPD KALSEL', '122', '1');
INSERT INTO `bank` VALUES ('62', 'BPD KALIMANTAN BARAT', '123', '1');
INSERT INTO `bank` VALUES ('63', 'BPD KALTIM', '124', '1');
INSERT INTO `bank` VALUES ('64', 'BPD KALTENG', '125', '1');
INSERT INTO `bank` VALUES ('65', 'BPD SULSEL', '126', '1');
INSERT INTO `bank` VALUES ('66', 'BANK SULUT', '127', '1');
INSERT INTO `bank` VALUES ('67', 'BPD NTB', '128', '1');
INSERT INTO `bank` VALUES ('68', 'BPD BALI', '129', '1');
INSERT INTO `bank` VALUES ('69', 'BANK NTT', '130', '1');
INSERT INTO `bank` VALUES ('70', 'BANK MALUKU', '131', '1');
INSERT INTO `bank` VALUES ('71', 'BPD PAPUA', '132', '1');
INSERT INTO `bank` VALUES ('72', 'BANK BENGKULU', '133', '1');
INSERT INTO `bank` VALUES ('73', 'BPD SULAWESI TENGAH', '134', '1');
INSERT INTO `bank` VALUES ('74', 'BANK SULTRA', '135', '1');
INSERT INTO `bank` VALUES ('75', 'BANK NUSANTARA PARAHYANGAN', '145', '1');
INSERT INTO `bank` VALUES ('76', 'BANK SWADESI', '146', '1');
INSERT INTO `bank` VALUES ('77', 'BANK MUAMALAT', '147', '1');
INSERT INTO `bank` VALUES ('78', 'BANK MESTIKA', '151', '1');
INSERT INTO `bank` VALUES ('79', 'BANK METRO EXPRESS', '152', '1');
INSERT INTO `bank` VALUES ('80', 'BANK SHINTA INDONESIA', '153', '1');
INSERT INTO `bank` VALUES ('81', 'BANK MASPION', '157', '1');
INSERT INTO `bank` VALUES ('82', 'BANK HAGAKITA', '159', '1');
INSERT INTO `bank` VALUES ('83', 'BANK GANESHA', '161', '1');
INSERT INTO `bank` VALUES ('84', 'BANK WINDU KENTJANA', '162', '1');
INSERT INTO `bank` VALUES ('85', 'HALIM INDONESIA BANK', '164', '1');
INSERT INTO `bank` VALUES ('86', 'BANK HARMONI INTERNATIONAL', '166', '1');
INSERT INTO `bank` VALUES ('87', 'BANK KESAWAN', '167', '1');
INSERT INTO `bank` VALUES ('88', 'BANK TABUNGAN NEGARA (PERSERO)', '200', '1');
INSERT INTO `bank` VALUES ('89', 'BANK HIMPUNAN SAUDARA 1906, TBK .', '212', '1');
INSERT INTO `bank` VALUES ('90', 'BANK TABUNGAN PENSIUNAN NASIONAL', '213', '1');
INSERT INTO `bank` VALUES ('91', 'BANK SWAGUNA', '405', '1');
INSERT INTO `bank` VALUES ('92', 'BANK JASA ARTA', '422', '1');
INSERT INTO `bank` VALUES ('93', 'BANK MEGA', '426', '1');
INSERT INTO `bank` VALUES ('94', 'BANK JASA JAKARTA', '427', '1');
INSERT INTO `bank` VALUES ('95', 'BANK BUKOPIN', '441', '1');
INSERT INTO `bank` VALUES ('96', 'BANK SYARIAH MANDIRI', '451', '1');
INSERT INTO `bank` VALUES ('97', 'BANK BISNIS INTERNASIONAL', '459', '1');
INSERT INTO `bank` VALUES ('98', 'BANK SRI PARTHA', '466', '1');
INSERT INTO `bank` VALUES ('99', 'BANK JASA JAKARTA', '472', '1');
INSERT INTO `bank` VALUES ('100', 'BANK BINTANG MANUNGGAL', '484', '1');
INSERT INTO `bank` VALUES ('101', 'BANK BUMIPUTERA', '485', '1');
INSERT INTO `bank` VALUES ('102', 'BANK YUDHA BHAKTI', '490', '1');
INSERT INTO `bank` VALUES ('103', 'BANK MITRANIAGA', '491', '1');
INSERT INTO `bank` VALUES ('104', 'BANK AGRO NIAGA', '494', '1');
INSERT INTO `bank` VALUES ('105', 'BANK INDOMONEX', '498', '1');
INSERT INTO `bank` VALUES ('106', 'BANK ROYAL INDONESIA', '501', '1');
INSERT INTO `bank` VALUES ('107', 'BANK ALFINDO', '503', '1');
INSERT INTO `bank` VALUES ('108', 'BANK SYARIAH MEGA', '506', '1');
INSERT INTO `bank` VALUES ('109', 'BANK INA PERDANA', '513', '1');
INSERT INTO `bank` VALUES ('110', 'BANK HARFA', '517', '1');
INSERT INTO `bank` VALUES ('111', 'PRIMA MASTER BANK', '520', '1');
INSERT INTO `bank` VALUES ('112', 'BANK PERSYARIKATAN INDONESIA', '521', '1');
INSERT INTO `bank` VALUES ('113', 'BANK AKITA', '525', '1');
INSERT INTO `bank` VALUES ('114', 'LIMAN INTERNATIONAL BANK', '526', '1');
INSERT INTO `bank` VALUES ('115', 'ANGLOMAS INTERNASIONAL BANK', '531', '1');
INSERT INTO `bank` VALUES ('116', 'BANK DIPO INTERNATIONAL', '523', '1');
INSERT INTO `bank` VALUES ('117', 'BANK KESEJAHTERAAN EKONOMI', '535', '1');
INSERT INTO `bank` VALUES ('118', 'BANK UIB', '536', '1');
INSERT INTO `bank` VALUES ('119', 'BANK ARTOS IND', '542', '1');
INSERT INTO `bank` VALUES ('120', 'BANK PURBA DANARTA', '547', '1');
INSERT INTO `bank` VALUES ('121', 'BANK MULTI ARTA SENTOSA', '548', '1');
INSERT INTO `bank` VALUES ('122', 'BANK MAYORA', '553', '1');
INSERT INTO `bank` VALUES ('123', 'BANK INDEX SELINDO', '555', '1');
INSERT INTO `bank` VALUES ('124', 'BANK VICTORIA INTERNATIONAL', '566', '1');
INSERT INTO `bank` VALUES ('125', 'BANK EKSEKUTIF', '558', '1');
INSERT INTO `bank` VALUES ('126', 'CENTRATAMA NASIONAL BANK', '559', '1');
INSERT INTO `bank` VALUES ('127', 'BANK FAMA INTERNASIONAL', '562', '1');
INSERT INTO `bank` VALUES ('128', 'BANK SINAR HARAPAN BALI', '564', '1');
INSERT INTO `bank` VALUES ('129', 'BANK HARDA', '567', '1');
INSERT INTO `bank` VALUES ('130', 'BANK FINCONESIA', '945', '1');
INSERT INTO `bank` VALUES ('131', 'BANK MERINCORP', '946', '1');
INSERT INTO `bank` VALUES ('132', 'BANK MAYBANK INDOCORP', '947', '1');
INSERT INTO `bank` VALUES ('133', 'BANK OCBC – INDONESIA', '948', '1');
INSERT INTO `bank` VALUES ('134', 'BANK CHINA TRUST INDONESIA', '949', '1');
INSERT INTO `bank` VALUES ('135', 'BANK COMMONWEALTH', '950', '1');
